### ISSUE TITLE
hardened_malloc configured incorrectly

### ISSUE THREAD

**Issue by SkewedZeppelin** [RagnarokOS/src#2]
https://github.com/RagnarokOS/src/blob/6f20618d8d7a36c0330e84373ea5f23d875696af/usr/lib/hardened_malloc/debian/etc/init.d/hardened_malloc#L15

Please see https://gist.github.com/SkewedZeppelin/7f293d64c1c651bdc21526519d9e192b

**Comment by IanLeCorbeau** [comment]
In Ragnarok, hardened_malloc.so is a symlink to the variant chosen by the user (both upstream variants are built, along with a custom one). It's also important to note that this init script (and the whole debian directory) needs an update. The package isn't being built right now and it's handled differently in the live ISO (hardened_malloc is compiled at boot to make use of march=native).
